### ISSUE TITLE
Google Play Pre-Launch-Report warning

### ISSUE THREAD

**Issue by nohli** [erickzanardo/ocarina#2]
```
API Landroid/media/AudioTrack;->getLatency()I
72 occurrences identified. Only unique stack traces are shown.
```

```
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/media/AudioTrack;->getLatency()I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at com.google.android.exoplayer2.audio.AudioTrackPositionTracker.<init>(AudioTrackPositionTracker.java:21)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.<init>(DefaultAudioSink.java:31)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.<init>(DefaultAudioSink.java:5)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.<init>(DefaultAudioSink.java:1)
	at com.google.android.exoplayer2.DefaultRenderersFactory.a(DefaultRenderersFactory.java:20)
	at com.google.android.exoplayer2.DefaultRenderersFactory.a(DefaultRenderersFactory.java:55)
	at com.google.android.exoplayer2.SimpleExoPlayer.<init>(SimpleExoPlayer.java:81)
	at com.google.android.exoplayer2.SimpleExoPlayer.<init>(SimpleExoPlayer.java:16)
	at com.google.android.exoplayer2.SimpleExoPlayer$Builder.build(SimpleExoPlayer.java:28)
	at xyz.erick.ocarina.OcarinaPlayer.load(OcarinaPlayer.java:7)
	at xyz.erick.ocarina.OcarinaPlugin.onMethodCall(OcarinaPlugin.java:141)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

```
 StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Landroid/media/AudioTrack;->getLatency()I
	at android.os.StrictMode.lambda$static$1(StrictMode.java:428)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Class.java)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2075)
	at java.lang.Class.getMethod(Class.java:2063)
	at java.lang.Class.getMethod(Class.java:1690)
	at com.google.android.exoplayer2.audio.AudioTrackPositionTracker.<init>(AudioTrackPositionTracker.java:21)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.<init>(DefaultAudioSink.java:31)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.<init>(DefaultAudioSink.java:5)
	at com.google.android.exoplayer2.audio.DefaultAudioSink.<init>(DefaultAudioSink.java:1)
	at com.google.android.exoplayer2.DefaultRenderersFactory.a(DefaultRenderersFactory.java:20)
	at com.google.android.exoplayer2.DefaultRenderersFactory.a(DefaultRenderersFactory.java:55)
	at com.google.android.exoplayer2.SimpleExoPlayer.<init>(SimpleExoPlayer.java:81)
	at com.google.android.exoplayer2.SimpleExoPlayer.<init>(SimpleExoPlayer.java:16)
	at com.google.android.exoplayer2.SimpleExoPlayer$Builder.build(SimpleExoPlayer.java:28)
	at xyz.erick.ocarina.OcarinaPlayer.load(OcarinaPlayer.java:7)
	at xyz.erick.ocarina.OcarinaPlugin.onMethodCall(OcarinaPlugin.java:141)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:17)
	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:57)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:4)
	at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:160)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by erickzanardo** [comment]
This happens because of and API used by Exoplayer and can be ignored as stated here: https://github.com/google/ExoPlayer/issues/5763
